#!/bin/zsh
echo "How old are you?"
read age

if [ $age -ge 16 ]
then 
	echo "You can drive"
elif [ $age -eq 15 ]
then 
	echo "You can drive next year"
else
	echo "You can't drive"
fi

echo "Hello $name"
